### ISSUE TITLE
Consider including post-babel artifacts in npm packge

### ISSUE THREAD

**Issue by cschwebk** [ivan-kleshnin/react-safe#2]
Your recent release, [v1.2.0](https://github.com/ivan-kleshnin/react-safe/releases/tag/v1.2.0), does not include post-babel artifacts in the npm package. Please consider including these in your next release, as some build tools, like `browserify`, do not run on `node_modules`. Thanks 😄 .

**Comment by ivan-kleshnin** [comment]
Hi @cschwebk! Thanks for the feedback. 

Could you clarify in what sense `browserify` doesn't run on `node_modules`? 
Last time I used `browserify` (3 years ago) it was able to do that. Google search seems to confirm that:

https://stackoverflow.com/questions/39321384/how-should-i-transform-es6-node-modules-with-browserify-and-babelify

> **by default**, transforms are not applied to files within the node_modules directory

My reasoning behind removal was that:

1) No build process on the lib side means you can customize it.
2) To my experience CommonJS modules cause behavior artefacts often than ES6

Saying that, I'm totally open to discussion and reconsideration.

**Comment by ivan-kleshnin** [comment]
In general, most problems with `node_modules` compilation can be solved by replacing `.babelrc` with `babel.config.js` as recommended here: https://babeljs.io/docs/en/configuration

**Comment by cschwebk** [comment]
Thanks for the replies @ivan-kleshnin, and apologies that my justification was not clear enough. I missed the all-important, **by default**.

I am aware that `browserify` and `babel` can be configured to include files in `node_modules`. Until now, it has not been necessary for us, as all of the ~200 other external packages we rely on have shipped ES5 code along with their ES6. It does appear though that this is the [direction the industry is moving in](https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages).

In the end it is your decision on how you want to publish your module, we don't have a problem pinning `react-safe` to `v1.1.1`.

**Comment by ivan-kleshnin** [comment]
I gave it a thought yesterday and I agree there are some ergonomic and performance problems with ES6 in `node_modules`. It's the case of theory vs practice where we should favor the latter. So I reconsider my choice and will publish `1.3` with a build. Thank you for the feedback!
