### ISSUE TITLE
Add an explanation about XSS injections

### ISSUE THREAD

**Issue by mfr-itr** [ivan-kleshnin/react-safe#3]
I think it would be very wise to add a proper warning about XSS injections in your README. As it is now, `dangerouslySetInnerHTML` looks harmless. If "a programmer considers [it] safe", they should take a look at https://zhenyong.github.io/react/tips/dangerously-set-inner-html.html or something.

**Comment by ivan-kleshnin** [comment]
Hi @mfr-itr. Thank you for the proposal! I agree with it, and I'm going to update the README soon.

**Comment by mfr-itr** [comment]
Alternatively, you could include a sanitation feature like https://github.com/cure53/DOMPurify.

**Comment by ivan-kleshnin** [comment]
True. But I'm afraid it's quite big and slow to be non-optional. So I'm leaning towards the first option.

**Comment by ivan-kleshnin** [comment]
Warning added. Thx again @mfr-itr
